//APRESENTAÇÃO

console.log("SISTEMA: Bem vindo jogador, por favor digite seu nome")
console.log("JOGADOR: Meu nome é doubleSword")
console.log("SISTEMA: Muito bem doubleSwords, a sua frente têm uma esfera de crsital ela ira dectecar seu nivel e verificar se você é digno")
console.log("NOTIFICAÇÃO: O jogador colocou a mão sobre a esfera e iniciou o processo de avaliação")
console.log("ESFERA: o nivel de experiência detectado é 9000 xp")

//VARIAVEIS

let nomeHeroi = "doubleSword"
let xp = 9000

//DEFINIÇÃO DE NIVEL DO JOGADOR

console.log("NOTIFICAÇÃO: Processando o nivel do jogador ")
let level
if(xp < 1000){
    level = "ferro"
}else if(xp <= 2000){
    level = "bronze"
}else if(xp <= 5000){
    level = "prata"
}else if(xp = 7000){
    level = "ouro"
}else if(xp = 9000){
    level = ascendente
}else if(xp <= 10000){
    level = "imortal"
}else if(xp >= 10001){
    level = "radiante"
}
//MENSAGEN FINAL

console.log("o heroi de nome " + nomeHeroi (" està no nivel de ") + level)
console.log("SISTEMA:você se provou digno jogador")







































































